assets:
  css:
    - bundles/itkcampaign/assets/build/itkcampaign.min.css
  js_prod:
    - bundles/itkcampaign/assets/build/itkcampaign.min.js

modules:

apps:
  itkCampaignApp:
    container: true
    files:
      - bundles/itkcampaign/apps/itkCampaignApp/itkCampaignApp.js
      - bundles/itkcampaign/apps/itkCampaignApp/directives/contenteditable.js
      - bundles/itkcampaign/apps/itkCampaignApp/campaign/itkCampaignController.js
    dependencies:
      - busModule
      - mainModule
      - ngRoute
      - bw.paging
      - pascalprecht.translate
      - datetimePicker
      - angularModalService
