services:
  # Overrides CoreBundle/Services/MiddlewareCommunication.
  os2display.middleware.communication:
    class: Os2Display\CampaignBundle\Service\MiddlewareCommunication
    arguments: ['@service_container', '@os2display.template_service', '@os2display.utility_service']
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron, priority: 1 }

  # Overrides CoreBundle/Services/MiddlewareService.
  os2display.middleware.service:
    class: Os2Display\CampaignBundle\Service\MiddlewareService
    arguments: ['@doctrine.orm.entity_manager', '@jms_serializer', '@os2display.core.cache', 300]
    public: true

  os2display.campaign_manager:
    class: Os2Display\CampaignBundle\Service\CampaignManager
    arguments:
      - '@os2display.entity_service'
      - '@os2display.security_manager'
      - '@os2display.group_manager'
      - '@doctrine.orm.entity_manager'
      - '@os2display.entity_manager'

  os2display.campaign_edit_voter:
    class: Os2Display\CampaignBundle\Security\EditVoter
    # parent: os2display.edit_voter
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.access.decision_manager'
      - '@os2display.security_manager'
    # public: false
    tags:
      - { name: security.voter }

  os2display.campaign.service.api_data:
    class: Os2Display\CampaignBundle\Service\ApiDataService
    arguments:
      - '@doctrine.orm.entity_manager'

  os2display.campaign.subscriber.api_data:
    class: Os2Display\CampaignBundle\Event\ApiDataSubscriber
    arguments:
      - '@os2display.campaign.service.api_data'
    tags:
      - { name: kernel.event_subscriber }

  os2display.campaign.subscriber.roles:
    class: Os2Display\CampaignBundle\Event\RolesSubscriber
    tags:
      - { name: kernel.event_subscriber }
