services:
  # Overrides CoreBundle/Services/MiddlewareCommunication.
  os2display.middleware.communication:
    class: Itk\CampaignBundle\Service\MiddlewareCommunication
    arguments: ['@service_container', '@os2display.template_service', '@os2display.utility_service']
    tags:
      - { name: kernel.event_listener, event: ik.cron, method: onCron, priority: 1 }
